### ISSUE TITLE
Date time error

### ISSUE THREAD

**Issue by smitas3400** [swoga/mikrotik-exporter#42]
Hell, newes firmware have changes to time now i get this error

ERR failed to parse datetime error="parsing time \"2023-06-26 00:32:53\" as \"Jan/02/2006 15:04:05\": cannot parse \"2023-06-26 00:32:53\" as \"Jan\"" command_no=1 connection_no=0 metric_name=last_link_up module=interface request_no=6 sentence_no=0 target=test word="2023-06-26 00:32:53"

**Comment by swoga** [comment]
Hi,
which RouterOS version are you using?

**Comment by smitas3400** [comment]
7.10

**Comment by swoga** [comment]
I am currently using this application only with v6 and am surprised that it works at all with v7.
Many fields have different names and probably require their own modules.

I will gladly accept PRs which provide v7 compatibility.
