### ISSUE TITLE
Compliance prometheus

### ISSUE THREAD

**Issue by Sn0wAlice** [swoga/mikrotik-exporter#76]
Hello

i was working on the installation of the exporter for SNMP services, all works fine !

But is that any way to me prometheus compliant ?
Url format `/probe?target=xxx` generate failure on the config need to create a proxy rewrite rules to make it works..

Can the route `/metrics` can expose all data of all the snmp monitored system ? OR JUST changing the URL path to __remove__ the parameter system and replace by `/probe/TARGET_NAME` ?

tanks you

**Comment by swoga** [comment]
Hi!

Prometheus calls this schema the multi-target exporter pattern: https://prometheus.io/docs/guides/multi-target-exporter/
You have to use relabeling to set the `target`.
The blackbox_exporter includes a short example config: https://github.com/prometheus/blackbox_exporter?tab=readme-ov-file#prometheus-configuration

**Comment by Sn0wAlice** [comment]
Okay works fine, thank you. :)
